[build]
    publish = "out"
    command = "npm run build"

[build.environment]
    NETLIFY_NEXT_PLUGIN_SKIP = "true"
    NODE_OPTIONS = "--max-old-space-size=4096"
    PYTHON_VERSION = "3.9"
    
[build.processing]
    skip_processing = false

[build.processing.images]
    compress = true
[functions]
  directory = "src/netlify/functions"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"
