[build]
    base = ""
    publish = ".next"
    command = "yarn build"
[functions]
  directory = "src/netlify/functions"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"
