[build]
    publish = "out"
    command = "npm run build"
    environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }
[functions]
  directory = "src/netlify/functions"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"
