name: Monitor Notion Published Status

on:
  # 毎時実行
  schedule:
    - cron: '0 * * * *'
  
  # 手動実行用
  workflow_dispatch:

jobs:
  check-notion-published:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fetch cache from previous run
        uses: actions/cache@v3
        with:
          path: .notion-published-cache.json
          key: notion-published-cache-${{ github.run_id }}
          restore-keys: notion-published-cache-

      - name: Check for changes in published status
        id: check-changes
        run: |
          node scripts/check-notion-published.js
          # 変更があった場合にのみ出力を設定
          if [ $? -eq 0 ]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_BLOG_DATABASE: ${{ secrets.NOTION_BLOG_DATABASE }}

      - name: Upload new cache
        uses: actions/cache/save@v3
        with:
          path: .notion-published-cache.json
          key: notion-published-cache-${{ github.run_id }}

      - name: Trigger Netlify Build
        # ステップの終了コードが0の場合は常に実行 
        # (check-changesスクリプトで変更を検出した場合のみ有効なのでここでは常に実行)
        if: steps.check-changes.outputs.changes_detected == 'true'
        run: |
          # Netlify Build Hookを呼び出す
          curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
